############################
# STEP 1 build executable binary
############################
FROM golang:1.18-alpine

RUN adduser \
    --disabled-password\
    --gecos "" \
    --home "/nonexinstent" \
    --shell "/sbin/nologin" \
    --no-create-home \
    --uid 65532 \
    ajitirto

WORKDIR /app
COPY . .

RUN go mod download
RUN go mod verify

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /server .

USER ajitirto:ajitirto

EXPOSE 8085

CMD [ "/server" ]
